stages:
  - test
  - deployServer

test:
  stage: test
  only:
    - develop
  script:
    - exit 0

deployServer:
  stage: deployServer
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y)'
    - mkdir -p ~/.ssh 
    - '[[ -f  /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $IP_SERVER >> ~/.ssh/known_hosts
  script:
    - echo "=== START DEPLOY ==="
    - ssh deploy@$IP_SERVER "source ~/.nvm/nvm.sh; cd course-cicd; git pull; npm i; pm2 restart server.js"
